// src/components/SpotifyPlayer.tsx
import { useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { RootState } from '@/store';
import { setSpotifyPlayback } from '@/store/slices/playerSlice';
import SpotifyWebApi from 'spotify-web-api-node';

interface SpotifyPlayerProps {
  spotifyApi: SpotifyWebApi;
}

export default function SpotifyPlayer({ spotifyApi }: SpotifyPlayerProps) {
  const dispatch = useDispatch();
  const { spotify } = useSelector((state: RootState) => state.player);
  const { accessToken } = useSelector((state: RootState) => state.auth.spotify);

  useEffect(() => {
    if (!accessToken) return;

    spotifyApi.setAccessToken(accessToken);

    const pollPlayback = async () => {
      try {
        const data = await spotifyApi.getMyCurrentPlaybackState();
        if (data.body) {
          dispatch(
            setSpotifyPlayback({
              isPlaying: data.body.is_playing,
              progress: data.body.progress_ms || 0,
              trackId: data.body.item?.id || null,
            })
          );
        }
      } catch (error) {
        console.error('Error polling Spotify playback:', error);
      }
    };

    pollPlayback();
    const interval = setInterval(pollPlayback, 1000);

    return () => clearInterval(interval);
  }, [accessToken, dispatch, spotifyApi]);

  if (!accessToken) {
    return (
      <div className="bg-surface-color rounded-lg p-6 text-center">
        <p className="text-gray-400">Connect your Spotify account to start playing</p>
      </div>
    );
  }

  return (
    <div className="bg-surface-color rounded-lg p-6">
      <div className="flex items-center justify-between mb-4">
        <h2 className="text-xl font-semibold">Spotify</h2>
        <div className="flex items-center space-x-2">
          <div
            className={`w-2 h-2 rounded-full ${
              spotify.isPlaying ? 'bg-green-500' : 'bg-gray-500'
            }`}
          />
          <span className="text-sm text-gray-400">
            {spotify.isPlaying ? 'Playing' : 'Paused'}
          </span>
        </div>
      </div>

      {spotify.trackId ? (
        <div>
          <p className="text-lg font-medium mb-2">Track ID: {spotify.trackId}</p>
          <p className="text-gray-400">Progress: {spotify.progress}ms</p>
        </div>
      ) : (
        <p className="text-gray-400">No track playing</p>
      )}
    </div>
  );
}

// src/app/_components/spotify-player/spotify-player.component.ts
import { Component, OnDestroy, inject, effect } from '@angular/core';
import { CommonModule } from '@angular/common';
import { PlayerService } from '../../_services/player.service';

declare global {
  interface Window {
    onSpotifyWebPlaybackSDKReady: () => void;
    Spotify: {
      Player: new (config: {
        name: string;
        getOAuthToken: (callback: (token: string) => void) => void;
        volume: number;
      }) => {
        addListener: (event: string, callback: (data: any) => void) => void;
        connect: () => Promise<boolean>;
      };
    };
  }
}

@Component({
  selector: 'app-spotify-player',
  templateUrl: './spotify-player.component.html',
  standalone: true,
  imports: [CommonModule]
})
export class SpotifyPlayerComponent implements OnDestroy {
  private readonly playerService = inject(PlayerService);
  readonly spotify_ = this.playerService.spotify_;
  readonly accessToken_ = this.playerService.spotifyAccessToken_;
  private deviceId: string | null = null;

  constructor() {
    effect(() => {
      const accessToken = this.accessToken_();
      if (accessToken) {
        this.initializePlayer();
      }
    });

    effect(() => {
      const spotify = this.spotify_();
      if (spotify.trackId && this.deviceId) {
        this.loadTrack(spotify.trackId);
      }
    });
  }

  ngOnDestroy() {
    // Clean up any resources if needed
  }

  private initializePlayer() {
    // Initialize Spotify Web Playback SDK
    const script = document.createElement('script');
    script.src = 'https://sdk.scdn.co/spotify-player.js';
    script.async = true;
    document.body.appendChild(script);

    window.onSpotifyWebPlaybackSDKReady = () => {
      const player = new window.Spotify.Player({
        name: 'Web Playback SDK',
        getOAuthToken: (cb: (token: string) => void) => { cb(this.accessToken_() || ''); },
        volume: 0.5
      });

      player.addListener('ready', ({ device_id }: { device_id: string }) => {
        console.log('Ready with Device ID', device_id);
        this.deviceId = device_id;
      });

      player.addListener('not_ready', ({ device_id }: { device_id: string }) => {
        console.log('Device ID has gone offline', device_id);
        if (this.deviceId === device_id) {
          this.deviceId = null;
        }
      });

      player.addListener('player_state_changed', (state: { is_playing: boolean; position: number; track_window: { current_track: { id: string } } }) => {
        if (state) {
          this.playerService.setSpotifyPlayback(
            state.is_playing,
            state.position,
            state.track_window.current_track.id
          );
        }
      });

      player.connect();
    };
  }

  private loadTrack(trackId: string) {
    if (!this.deviceId) return;

    // Load track using Spotify Web API
    fetch(`https://api.spotify.com/v1/me/player/play?device_id=${this.deviceId}`, {
      method: 'PUT',
      headers: {
        'Authorization': `Bearer ${this.accessToken_()}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        uris: [`spotify:track:${trackId}`]
      })
    });
  }
} 
@if (accessToken_() === null) {
  <div class="bg-surface-color rounded-lg p-6 text-center">
    <p class="text-gray-400">Connect your Spotify account to start playing</p>
  </div>
}

@if (accessToken_() !== null) {
  <div class="bg-surface-color rounded-lg p-6">
    <div class="flex items-center justify-between mb-4">
      <h2 class="text-xl font-semibold">Spotify</h2>
      <div class="flex items-center space-x-2">
        <div
          class="w-2 h-2 rounded-full"
          [class.bg-green-500]="spotify_().isPlaying"
          [class.bg-gray-500]="!spotify_().isPlaying"
        ></div>
        <span class="text-sm text-gray-400">
          {{ spotify_().isPlaying ? 'Playing' : 'Paused' }}
        </span>
      </div>
    </div>

    @if (spotify_().trackId) {
      <div>
        <p class="text-lg font-medium mb-2">Track ID: {{ spotify_().trackId }}</p>
        <p class="text-gray-400">Progress: {{ spotify_().progress }}ms</p>
      </div>
    } @else {
      <p class="text-gray-400">No track playing</p>
    }
  </div>
}
